apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /root/certs/ca.crt
    server: https://fqdn-control.udev.local:6443
  name: cluster
contexts:
- context:
    cluster: cluster
tls-san:
  - "fqdn-control.udev.local"
  - "kubernetes"
  - "kubernetes.default"
  - "kubernetes.default.svc"
  - "kubernetes.default.svc.cluster.local"
  - "localhost"
  - "fqdn-control-machine-name.udev.local"