rke2_cluster:
  children:
    rke2_servers:
      hosts:
        fqdn-control.udev.local:
          control_plane_hostname: fqdn-control.udev.local
    rke2_agents:
      hosts:
        fqdn-worker01.udev.local:
        fqdn-worker02.udev.local:
          node_labels:
          - agent2Label=true
all:
  vars:
    install_rke2_version: v1.30.1+rke2r1