---
# HTML BUTTONS CAN BE MODIFIED
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-homepage
  namespace: homepage
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>RKE2 Cluster Services</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                height: 100vh;
                background-image: url('./container-background.png');/* Update with the correct path */
                background-size: cover;
                background-position: center;
                background-repeat: no-repeat;
            }
            .banner {
                background-color: rgba(40, 167, 69, 0.8);
                color: white;
                padding: 10px;
                text-align: center;
                font-weight: bold;
                width: 100%;
                position: fixed;
                top: 0;
                left: 0;
            }
            h1 {
                margin-top: 60px;
                text-align: center;
                color: black;
            }
            .button-container {
                display: flex;
                flex-direction: column;
                align-items: center;
                gap: 15px;
                margin-top: 20px;
                width: 100%;
                max-width: 300px;
            }
            .service-button {
                padding: 15px 30px;
                font-size: 18px;
                border: none;
                border-radius: 5px;
                background-color: rgba(0, 123, 255, 0.8);
                color: white;
                cursor: pointer;
                text-decoration: none;
                text-align: center;
                width: 100%;
                transition: background-color 0.3s;
            }
            .service-button:hover {
                background-color: rgba(0, 86, 179, 0.8);
            }
        </style>
    </head>
    <body>

        <div class="banner">This site may contain CUI</div>

        <h1>luster Services</h1>

        <div class="button-container">
            <a href="https://argocd.fqdn-control.udev.local" class="service-button" target="_blank">ArgoCD</a>
            <a href="https://harbor.fqdn-control.udev.local" class="service-button" target="_blank">Harbor</a>
            <a href="https://minio.fqdn-control.udev.local" class="service-button" target="_blank">Minio</a>
            <a href="https://prometheus.fqdn-control.udev.local" class="service-button" target="_blank">Prometheus</a>
            <a href="https://gitlab.com" class="service-button" target="_blank">Gitlab CSDE</a> 
            <a href="https://jira.com" class="service-button" target="_blank">Jira CSDE</a>
        </div>

    </body>
    </html>

