---
# cleaner/tasks/main.yml
- name: Uninstall RKE2 Cluster
  ansible.builtin.shell: /usr/local/bin/rke2-uninstall.sh
  ignore_errors: yes
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Delete Certs Directory
  ansible.builtin.file:
    path: /root/certs
    state: absent

- name: Delete RKE2 Artifacts Directory
  ansible.builtin.file:
    path: /root/rke2-artifacts
    state: absent

- name: Disable Minio Service
  ansible.builtin.systemd:
    name: minio
    state: stopped
    enabled: no

- name: Delete Minio Environment
  ansible.builtin.file:
    path: /etc/default/minio
    state: absent

- name: Delete Minio Service File
  ansible.builtin.file:
    path: /usr/lib/systemd/system/minio.service
    state: absent

- name: Delete Data Directory
  ansible.builtin.file:
    path: /root/data
    state: absent

- name: Delete All .key Files in /root
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /root/*.key

- name: Delete All .crt Files in /root
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /root/*.crt
